"""Pin this project's dependencies to the versions the vendored stack locks.

Reads third_party/microduck_rl/uv.lock and rewrites the
`constraint-dependencies` block in pyproject.toml so `uv lock` resolves the
exact versions Pollen tests against. Run after updating the vendored copy:

    uv run python scripts/sync_vendor_constraints.py && uv lock
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "third_party" / "microduck_rl" / "uv.lock"
PYPROJECT = ROOT / "pyproject.toml"
BEGIN = "# BEGIN vendor constraints (generated by scripts/sync_vendor_constraints.py)"
END = "# END vendor constraints"
SKIP = {"mjlab-microduck"}


def main() -> None:
    lock = tomllib.loads(LOCK.read_text())
    packages = lock.get("package", [])
    counts: dict[str, int] = {}
    for pkg in packages:
        counts[pkg["name"]] = counts.get(pkg["name"], 0) + 1

    pins = {}
    for pkg in packages:
        name, version, source = pkg["name"], pkg.get("version"), pkg.get("source", {})
        if name in SKIP or not version:
            continue
        if "registry" not in source:  # git/path sources are pinned by [tool.uv.sources]
            continue
        # Packages locked at different versions per platform (torch and its
        # CUDA wheels on aarch64 vs x86_64) are left to torch's own pins.
        if counts[name] > 1:
            continue
        pins[name] = version

    lines = [BEGIN, "constraint-dependencies = ["]
    lines += [f'    "{n}=={v}",' for n, v in sorted(pins.items())]
    lines += ["]", END]
    block = "\n".join(lines)

    text = PYPROJECT.read_text()
    if BEGIN in text:
        text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, text, flags=re.S)
    else:
        text = text.replace("[tool.uv.sources]", block + "\n\n[tool.uv.sources]", 1)

    # Git dependencies: pin the exact commit the vendored lock resolved (a
    # branch name alone drifts — a newer BAM commit renamed actuator kwargs).
    # uv honours a path dependency's OWN [tool.uv.sources] for its deps, so
    # the pin goes into both pyproject files (a documented local patch, see
    # VENDORED.md).
    vendored = LOCK.parent / "pyproject.toml"
    vtext = vendored.read_text()
    for pkg in packages:
        git = pkg.get("source", {}).get("git")
        if not git or "#" not in git:
            continue
        url, rev = git.split("#", 1)
        url = url.split("?", 1)[0]
        line = f'{pkg["name"]} = {{ git = "{url}", rev = "{rev}" }}'
        pattern = rf'^{re.escape(pkg["name"])} = \{{ git = .*\}}$'
        text, n = re.subn(pattern, line, text, flags=re.M)
        vtext, vn = re.subn(pattern, line, vtext, flags=re.M)
        if n or vn:
            print(f"Pinned {pkg['name']} to {rev[:12]}")
    vendored.write_text(vtext)

    PYPROJECT.write_text(text)
    print(f"Wrote {len(pins)} constraints from {LOCK.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
